import{S as m,i as a,a as y}from"./assets/vendor-f144e563.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))g(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&g(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function g(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const h=document.getElementById("search-form"),p=document.getElementById("gallery"),l=document.getElementById("load-more");let n=1,i="";const d=40,b="44455355-2a7bcc134ac57944b610f09f9",w="https://pixabay.com/api/";let E=new m(".gallery a");const f=async(o,s)=>{try{return(await y.get(w,{params:{key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:d}})).data}catch(e){throw console.error("Error fetching images:",e),a.show({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight",backgroundColor:"lightcoral",color:"white"}),e}},u=o=>{const s=o.map(e=>`
    <a href="${e.largeImageURL}" class="photo-card">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="info-item"><b>Views:</b> ${e.views}</p>
        <p class="info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `).join("");p.insertAdjacentHTML("beforeend",s),E.refresh()},L=()=>{p.innerHTML=""},v=async o=>{o.preventDefault();const s=h.searchQuery.value.trim();if(!s){a.show({title:"Error",message:"Please enter a search query.",position:"topRight",backgroundColor:"lightcoral",color:"white"});return}i=s,n=1,L(),l.style.display="none";try{const e=await f(i,n);if(e.hits.length===0){a.show({title:"Error",message:`No images found for "${i}". Please try again.`,position:"topRight",backgroundColor:"lightcoral",color:"white"});return}u(e.hits),a.show({title:"Success",message:`Found ${e.totalHits} images for "${i}".`,position:"topRight",backgroundColor:"lightgreen",color:"white"}),e.hits.length===d&&(l.style.display="block")}catch(e){console.error("Error fetching images:",e)}},I=async()=>{n+=1;try{const o=await f(i,n);u(o.hits),n*d>=o.totalHits&&(l.style.display="none",a.show({title:"Info",message:"You've reached the end of search results.",position:"topRight",backgroundColor:"lightcoral",color:"white"}))}catch(o){console.error("Error fetching more images:",o),a.show({title:"Error",message:"Failed to fetch more images. Please try again later.",position:"topRight",backgroundColor:"lightcoral",color:"white"})}};h.addEventListener("submit",v);l.addEventListener("click",I);
//# sourceMappingURL=commonHelpers.js.map
